##Converts something from .obj to 'VL32' format. THen the `VL32` format to something we can use in python
#by Daniel Chu
#
# VL32 format spec: https://eisenwave.github.io/voxel-compression-docs/file_formats/vl32.html
import matplotlib.pyplot as plt
import os
import sys, time, pdb
import argparse
import threading
#External custom modules
from coordinateConversionMath import * #
from fileConversionFunctions import *
from cConversionFunctions import *
import win32pipe, win32file, struct
from PIL import Image, ImageDraw
from io import BytesIO


#defines
##########################################################
DEFAULT_OBJ_FILEPATH = "tea.obj"
HELPSTRING = '''
.obj 2 .hvox tool by Daniel Chu
for use with CMPE2965 3D hologram project

example usage: py voxelConversion.py tea.obj -dv
'''

SLICE_COUNT = 16#default is 16, this can be overridden in args when called
BOARD_WIDTH = 16
BOARD_HEIGHT = 32

HEADER_OUTPUT_FILENAME = "voxelData.h"

#globals
##########################################################
args = None
parser = None
bounceMultiplier = 3
#Utility/General
##########################################################

def plotVoxels(voxels):
    '''
    Plot converted voxels using mat plot lib 3D projection plot
    
    :param voxels: List of voxels (x, y, z)
    '''
    xList, yList, zList = zip(*voxels)#unpack coords for matplot lib
    ##setup minimum matplotlib 3D plot
    fig = plt.figure()
    ax = fig.add_subplot(111, projection="3d")
    ax.scatter(xList, yList, zList, marker='s', s=20)
    ax.set_xlabel("X axis")
    ax.set_ylabel("Y axis")
    ax.set_zlabel("Z axis")
    plt.show()

def plotPolarSlice(cylindrical, height):
    '''
    Plot a horizontal slice of polar coord
    :param height: the height to make the slice at
    '''
    filteredVoxels = [(theta, r) for theta, r, h in cylindrical if h == height]
    theta, r = zip(*filteredVoxels)
    fig, ax = plt.subplots(subplot_kw={'projection' : 'polar'})
    ax.scatter(theta, r, color="blue", linewidth=2)
    plt.show()

def addCylindricalToImage(image, angle, frame):
    '''
    Add Cylindrical info as text to PIL image
    
    :param image: Description
    :param angle: Description
    :param frame: Description
    '''
    draw = ImageDraw.Draw(image)
    #text fields
    text = f"""
H+ {frame}

    """
    draw.multiline_text((0,0), text, fill = "black")

def convertFullToPackedBytes():
    '''
    Perfom the entire conversion process from .obj to packed bytes

    return: Custom packed bytes in list [(nth rotation, height, nth led)]
    '''
    global args, parser, SLICE_COUNT, BOARD_WIDTH, BOARD_HEIGHT
    ##Convert everything...
    objFilepath = argsGetFilepath()
    #load the obj and convert the coords to quantized cylindrical
    print(f"converting {objFilepath} to cartesian voxels...")
    sys.stdout.flush()
    cartesianVoxels = getVoxelsFromObj(objFilepath, args.fillVoxels)
    print(f"converting cartesian to cylindrical...")
    sys.stdout.flush()
    cylindricalVoxels = cartesianList2Cylindrical(cartesianVoxels)
    print(f"quantizing cylindrical coordinates...")
    sys.stdout.flush()
    quantizedVoxels = cylindricalList2Quantized(cylindricalVoxels, SLICE_COUNT, BOARD_WIDTH, BOARD_HEIGHT)
    #prep change the voxel format to match what is needed in C
    print(f"packing voxel data for pipe transfer to UI...")
    sys.stdout.flush()
    flatBits = convertVoxelsToFlatList(quantizedVoxels, SLICE_COUNT, BOARD_WIDTH, BOARD_HEIGHT)
    packedBytes = packFlattenedVoxelsToBytes(flatBits)
    return packedBytes, objFilepath, quantizedVoxels, len(flatBits), cylindricalVoxels


#arg actions
##########################################################
def actionDebugVisualize():
    '''
    visualize .obj in matplotlib as 3d plot
    '''
    objFilepath = argsGetFilepath()
    voxels = getVoxelsFromObj(objFilepath, args.fillVoxels)#get the voxels from file
    print(f"plotting voxels...")
    sys.stdout.flush()
    plotVoxels(voxels)#visualize the voxels for debug

def actionConvertToHeader():
    '''
    convert .obj file to a C header in quantized cylindrical coords
    '''
    global SLICE_COUNT, BOARD_WIDTH, BOARD_HEIGHT

    packedBytes, objFilepath, quantizedVoxels, flatBitCount, _  = convertFullToPackedBytes()
    #build the output string
    dataStringLines = []
    valuesPerLine = 16#change the to change how long each data segment is in the data formatting
    for i in range(0, len(packedBytes), valuesPerLine):
        chunk = packedBytes[i:i + valuesPerLine]
        line = "    " + ", ".join(f"0x{b:02X}" for b in chunk)
        if i + valuesPerLine < len(packedBytes):
            line += ","
        dataStringLines.append(line)
    dataString = "\n".join(dataStringLines)
    outputString = f'''
// Data auto generated by 3D hologram VoxelConversion tool
//  model source file: {objFilepath}
#define MVOX_VOXEL_SLICES {SLICE_COUNT}
#define MVOX_VOXEL_HEIGHT {BOARD_HEIGHT}
#define MVOX_VOXEL_WIDTH {BOARD_WIDTH}
#define MVOX_VOXEL_COUNT {len(quantizedVoxels)}//The number of bits = 1
#define MVOX_VOXEL_BIT_COUNT {flatBitCount}
#define MVOX_VOXEL_BYTE_COUNT {len(packedBytes)}

const uint8_t debugMvox_voxelData[MVOX_VOXEL_BYTE_COUNT] = {{
{dataString}
}};
'''
    f = open(HEADER_OUTPUT_FILENAME, "w")
    f.write(outputString)


def actionConvertToPipe():
    '''
    convert an .obj file to custom byte array and return in a windows pipe
    '''
    global args, parser, SLICE_COUNT, BOARD_WIDTH, BOARD_HEIGHT
    packedBytes, objFilepath, _, _, _ = convertFullToPackedBytes()
    #Send the frame over pipe
    print("Writing voxel data to pipe...")
    sys.stdout.flush()
    pipeName = r'\\.\pipe\VoxelPipe'
    try:
        handle = win32file.CreateFile(
            pipeName,
            win32file.GENERIC_WRITE,
            0, None,
            win32file.OPEN_EXISTING,
            0, None
        )    
    except:
        print(f"[ERROR] named pipe {pipeName} not found!! (has the UI process created the pipe yet? )")
        sys.stdout.flush()
        return
    data = bytearray(packedBytes)
    win32file.WriteFile(handle, data)
    print(f"finished converting {objFilepath}!")
    sys.stdout.flush()

def actionConvertToAnimatedPipe():
    '''
    convert an .obj file to custom byte array animation and return in a windows pipe
    
    writes a header of the format
        struct{
            char[] header = {'V','O','X'},
            UINT64 pipeMessageSize = size of header + data in bytes// little endian
            UINT32 frameCount = frameCount//little endian
        }
    
    followed by the voxel data
    '''
    global args, parser, SLICE_COUNT, BOARD_WIDTH, BOARD_HEIGHT
    ##Convert everything...
    objFilepath = argsGetFilepath()
    #load the obj and convert the coords to quantized cylindrical
    print(f"converting {objFilepath} to cartesian voxels...")
    sys.stdout.flush()
    cartesianVoxels = getVoxelsFromObj(objFilepath, args.fillVoxels)
    print(f"converting cartesian to cylindrical...")
    sys.stdout.flush()
    cylindricalVoxels = cartesianList2Cylindrical(cartesianVoxels)
    print(f"quantizing cylindrical coordinates...")
    sys.stdout.flush()
    quantizedVoxels = cylindricalList2Quantized(cylindricalVoxels, SLICE_COUNT, BOARD_WIDTH, BOARD_HEIGHT)
    ## Simple vertical animation...
    print(f"Performing vertical transforms for simple animation")
    sys.stdout.flush()
    maxHeight = max(h for _, h, _ in quantizedVoxels)
    maxOffset = (BOARD_HEIGHT - 1) - maxHeight
    if maxOffset < 0:
        print("Model already exceeds board height!")
        sys.stdout.flush()
        return
    offsets = list(range(0, maxOffset + 1)) + list(range(maxOffset - 1, -1 ,-1))
    offsets = [x for x in offsets for _ in range(bounceMultiplier)]# repeat the frame N times to control speed...
    animatedFrames = []
    animatedFrames.extend(packFlattenedVoxelsToBytes(convertVoxelsToFlatList(quantizedVoxels, SLICE_COUNT, BOARD_WIDTH, BOARD_HEIGHT)))
    frameCount = 1
    frameSize = len(quantizedVoxels)
    for currentOffset in offsets:#perform all the transformations... pack the data here to not overwhelm the converter
        currentFrame = [(sliceN, h + currentOffset, r) for sliceN, h, r in quantizedVoxels]
        currentFrameFlatList = convertVoxelsToFlatList(currentFrame, SLICE_COUNT, BOARD_WIDTH, BOARD_HEIGHT)
        currentFramePacked = packFlattenedVoxelsToBytes(currentFrameFlatList)
        animatedFrames.extend(currentFramePacked)
        frameCount += 1
    #Send the data to the pipe
    data = bytearray(animatedFrames)
    print(f"writing pipe header w/ frameCount:{frameCount}")
    sys.stdout.flush()
    headerSize = 3 + 8 + 4#need size of header before the header is made... chicken and the egg... write this manually ):
    headerStruct = (b'VOX'  + #header data....
                    struct.pack('<Q', headerSize + len(data)) + 
                    struct.pack('<I', frameCount)
    )
    pipeName = r'\\.\pipe\VoxelPipe' #open the pipe...
    try:
        handle = win32file.CreateFile(
            pipeName,
            win32file.GENERIC_WRITE,
            0, None,
            win32file.OPEN_EXISTING,
            0, None
        )    
    except:
        print(f"[ERROR] named pipe {pipeName} not found!! (has the UI process created the pipe yet? )")
        sys.stdout.flush()
        return

    #Send the frame over pipe
    print("Writing voxel data to pipe...")
    sys.stdout.flush()
    win32file.WriteFile(handle, headerStruct + data)
    print(f"finished converting {objFilepath}!")
    sys.stdout.flush()

def actionDebugCylindrical():
    '''
    Output a test polar graph at the cylindrical pipeline step
    
    write the output to a .gif in script directory called "CylindricalAnimation.gif"
    '''
    global BOARD_HEIGHT
    plotImages = []
    _, _, _, _, cylindricalVoxels  = convertFullToPackedBytes()

    i = 0
    for currentH in range(BOARD_HEIGHT):
        filteredVoxels = [(theta, r) for theta, r, h in cylindricalVoxels if h == currentH]
        if len(filteredVoxels) == 0:
            theta , r = [],[]
        else:
            theta, r = zip(*filteredVoxels)
        fig, ax = plt.subplots(subplot_kw={'projection' : 'polar'})
        ax.scatter(theta, r, color="blue", linewidth=2)
        plt.title(f"horizontal polar slice")
        #plt.show()
        fig.canvas.draw()
        buffer = BytesIO()
        plt.savefig(buffer, format="png")
        buffer.seek(0)
        image = Image.open(buffer).convert("RGB")
        image.load()
        draw = ImageDraw.Draw(image)
        #text fields
        text = f"""
H =  {currentH}

"""
        draw.multiline_text((0,0), text, fill = "black")
        plotImages.append(image)
        buffer.close()
        plt.close()
        i += 1
    plotImages[0].save("CylindricalAnimation.gif", save_all = True, append_images = plotImages[1:], duration = 500, loop = 0)

    


# arg functions
##########################################################
def argsInit():
    '''
    Initialize parser and args. Parse all given args.
    '''
    global args, parser, SLICE_COUNT
    parser = argparse.ArgumentParser(description=HELPSTRING, formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument("objFilepath", nargs="?", help="Optional .obj file path")
    parser.add_argument("-d", "--debug", action="store_true")
    parser.add_argument("-dv", "--debugVisualize", action="store_true",  help="visualize .obj in matplotlib as 3d plot")
    parser.add_argument("-ch", "--convertHeader", action="store_true", help="convert .obj file to a C header in quantized cylindrical coords")
    parser.add_argument("-cp", "--convertPipe", action="store_true", help="convert .obj file to a byte array returned in a windows pipe. The UI pipe server MUST be running with named pipe VoxelPipe")
    parser.add_argument("-sc", "--sliceCount", type=int, help=f"override the default slicecount, default:{SLICE_COUNT}")
    parser.add_argument("-cpa","--convertPipeAnimated", action="store_true", help="convert .obj file to a byte array, formatted as an animation returned in a windows pipe. The UI pipe server MUST be running with named pipe VoxelPipe")
    parser.add_argument("-as", "--animationSpeed", type=int, help=f"Set the animation speed, default:{bounceMultiplier}")
    parser.add_argument("-fv", "--fillVoxels", action="store_true", help="Enable fill when converting voxels (takes a longer time)")
    parser.add_argument("-dcy", "--debugCylindrical", action="store_true", help="visualize slices of the cylindrical step")
    args = parser.parse_args()

def argsParseAndRunFlags():
    '''
    Look through all the given flag arguements and run what is needed based on what is given
    '''
    global args, parser, bounceMultiplier, SLICE_COUNT
    #value args
    if args.sliceCount:#override the default slice count if arg is given.
        SLICE_COUNT = args.sliceCount
    if args.animationSpeed:
        bounceMultiplier = args.animationSpeed
    
    #actions
    if args.debugVisualize:
        actionDebugVisualize()
    if args.convertHeader:
        actionConvertToHeader()
    if args.convertPipe:
        actionConvertToPipe()
    if args.convertPipeAnimated:
        actionConvertToAnimatedPipe()
    if args.debugCylindrical:
        actionDebugCylindrical()


def argsGetFilepath():
    '''
    get the filepath arg from args
    '''
    global args, parser
    objFilepath = DEFAULT_OBJ_FILEPATH
    if args.objFilepath:#set custom filepath if given
        givenPath = args.objFilepath
        if not os.path.exists(givenPath):#does the file exist
            parser.error(f"file {givenPath} not found")
            sys.stdout.flush()
        objFilepath = givenPath
    return objFilepath

#main
##########################################################
if __name__ == "__main__":
    #Handle Arg parse
    argsInit()
    argsParseAndRunFlags()
    if len(sys.argv) <= 1: #if no args are given, give some help...
        parser.print_help()
        sys.stdout.flush()