##Converts something from .obj to 'VL32' format. THen the `VL32` format to something we can use in python
#by Daniel Chu
#
# VL32 format spec: https://eisenwave.github.io/voxel-compression-docs/file_formats/vl32.html
import matplotlib.pyplot as plt
import os
import sys, time, pdb
import argparse
import threading
#External custom modules
from coordinateConversionMath import * #
from fileConversionFunctions import *
from cConversionFunctions import *



#defines
##########################################################
DEFAULT_OBJ_FILEPATH = "tea.obj"
HELPSTRING = '''
.obj 2 .hvox tool by Daniel Chu

example usage: py voxelConversion.py tea.obj -dv
'''

SLICE_COUNT = 16
BOARD_WIDTH = 16
BOARD_HEIGHT = 32

HEADER_OUTPUT_FILENAME = "voxelData.h"

#globals
##########################################################
args = None
parser = None

def plotVoxels(voxels):
    '''
    Plot converted voxels using mat plot lib 3D projection plot
    
    :param voxels: List of voxels (x, y, z)
    '''
    xList, yList, zList = zip(*voxels)#unpack coords for matplot lib
    ##setup minimum matplotlib 3D plot
    fig = plt.figure()
    ax = fig.add_subplot(111, projection="3d")
    ax.scatter(xList, yList, zList, marker='s', s=20)
    plt.show()

#arg actions
##########################################################
def actionDebugVisualize():
    '''
    visualize .obj in matplotlib as 3d plot
    '''
    objFilepath = argsGetFilepath()
    voxels = getVoxelsFromObj(objFilepath)#get the voxels from file
    print(f"debug {args.debug}")
    plotVoxels(voxels)#visualize the voxels for debug

def actionConvertToHeader():
    '''
    convert .obj file to a C header in quantized cylindrical coords
    '''
    global SLICE_COUNT, BOARD_WIDTH, BOARD_HEIGHT
    objFilepath = argsGetFilepath()
    #load the obj and convert the coords to quantized cylindrical
    cartesianVoxels = getVoxelsFromObj(objFilepath)
    cylindricalVoxels = cartesianList2Cylindrical(cartesianVoxels)
    quantizedVoxels = cylindricalList2Quantized(cylindricalVoxels, SLICE_COUNT, BOARD_WIDTH, BOARD_HEIGHT)
    #prep change the voxel format to match what is needed in C
    flatBits = convertVoxelsToFlatList(quantizedVoxels, SLICE_COUNT, BOARD_WIDTH, BOARD_HEIGHT)
    packedBytes = packFlattenedVoxelsToBytes(flatBits)
    #build the output string
    dataStringLines = []
    valuesPerLine = 16#change the to change how long each data segment is in the data formatting
    for i in range(0, len(packedBytes), valuesPerLine):
        chunk = packedBytes[i:i + valuesPerLine]
        line = "    " + ", ".join(f"0x{b:02X}" for b in chunk)
        if i + valuesPerLine < len(packedBytes):
            line += ","
        dataStringLines.append(line)
    dataString = "\n".join(dataStringLines)
    outputString = f'''
// Data auto generated by 3D hologram VoxelConversion tool
//  model source file: {objFilepath}
#define MVOX_VOXEL_SLICES {SLICE_COUNT}
#define MVOX_VOXEL_HEIGHT {BOARD_HEIGHT}
#define MVOX_VOXEL_WIDTH {BOARD_WIDTH}
#define MVOX_VOXEL_COUNT {len(quantizedVoxels)}//The number of bits = 1
#define MVOX_VOXEL_BIT_COUNT {len(flatBits)}
#define MVOX_VOXEL_BYTE_COUNT {len(packedBytes)}

const uint8_t debugMvox_voxelData[MVOX_VOXEL_BYTE_COUNT] = {{
{dataString}
}};
'''
    f = open(HEADER_OUTPUT_FILENAME, "w")
    f.write(outputString)


# arg functions
##########################################################
def argsInit():
    '''
    Initialize parser and args. Parse all given args.
    '''
    global args, parser
    parser = argparse.ArgumentParser(description=HELPSTRING, formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument("objFilepath", nargs="?", help="Optional .obj file path")
    parser.add_argument("-d", "--debug", action="store_true")
    parser.add_argument("-dv", "--debugVisualize", action="store_true",  help="visualize .obj in matplotlib as 3d plot")
    parser.add_argument("-ch", "--convertHeader", action="store_true", help="convert .obj file to a C header in quantized cylindrical coords")
    args = parser.parse_args()

def argsParseAndRunFlags():
    '''
    Look through all the given flag arguements and run what is needed based on what is given
    '''
    global args, parser
    if args.debugVisualize:
        actionDebugVisualize()
    if args.convertHeader:
        actionConvertToHeader()


def argsGetFilepath():
    '''
    get the filepath arg from args
    '''
    global args, parser
    objFilepath = DEFAULT_OBJ_FILEPATH
    if args.objFilepath:#set custom filepath if given
        givenPath = args.objFilepath
        if not os.path.exists(givenPath):#does the file exist
            parser.error(f"file {givenPath} not found")
        objFilepath = givenPath
    return objFilepath

#main
##########################################################
if __name__ == "__main__":
    #Handle Arg parse
    argsInit()
    argsParseAndRunFlags()
    if len(sys.argv) <= 1: #if no args are given, give some help...
        parser.print_help()
        sys.stdout.flush()